// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvHOs9eut-HagE1lFyGH8YQ3OTEsFkHzQ',
    appId: '1:889441316656:web:aeef078f4471c3286e62f5',
    messagingSenderId: '889441316656',
    projectId: 'pdfapp-f1485',
    authDomain: 'pdfapp-f1485.firebaseapp.com',
    storageBucket: 'pdfapp-f1485.firebasestorage.app',
    measurementId: 'G-QYNN3RWS4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0X9kTGqJkaRKScoHPl-fpehT_q6IYZA',
    appId: '1:889441316656:android:2bea57debcb5702c6e62f5',
    messagingSenderId: '889441316656',
    projectId: 'pdfapp-f1485',
    storageBucket: 'pdfapp-f1485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUQwyBvbkDv0gIpjD4waEsPTeBdQmEZ8',
    appId: '1:889441316656:ios:b1eda45591d987f66e62f5',
    messagingSenderId: '889441316656',
    projectId: 'pdfapp-f1485',
    storageBucket: 'pdfapp-f1485.firebasestorage.app',
    iosBundleId: 'com.example.pdfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrUQwyBvbkDv0gIpjD4waEsPTeBdQmEZ8',
    appId: '1:889441316656:ios:b1eda45591d987f66e62f5',
    messagingSenderId: '889441316656',
    projectId: 'pdfapp-f1485',
    storageBucket: 'pdfapp-f1485.firebasestorage.app',
    iosBundleId: 'com.example.pdfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvHOs9eut-HagE1lFyGH8YQ3OTEsFkHzQ',
    appId: '1:889441316656:web:70ccf7c5c8864f116e62f5',
    messagingSenderId: '889441316656',
    projectId: 'pdfapp-f1485',
    authDomain: 'pdfapp-f1485.firebaseapp.com',
    storageBucket: 'pdfapp-f1485.firebasestorage.app',
    measurementId: 'G-N7XCWYLL5H',
  );
}
